spring:
  application:
    name: spring-login-examples

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true

jwt:
  issuer: springadmin@example.com
  secret_key: study-springboot
